#!/usr/bin/env python3
# Copyright (c) 2026 JG Systems Consulting Ltd. MIT License (see LICENSE).
# SPDX-License-Identifier: MIT
"""
Generate docs/packs.html, the browsable skill-reference page (RR-B-30), from SKILLS.md.

The page is the single source's downstream artifact: it parses the SKILLS.md table
(slug, source licence, description) and the version from RELEASE-INFO.txt, then emits a
self-contained, design-system-compliant HTML page with a client-side filter box. No
third-party assets, no CDN. Regenerate after any pack/SKILLS.md change so it cannot drift
(RR-B-00). Em dashes are stripped from emitted copy (RR-B-28).
"""
import re
import sys
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def deslop(text: str) -> str:
    """Remove em dashes from emitted copy (RR-B-28). Replace with a comma + space,
    collapsing any surrounding spaces so ' — ' becomes ', '."""
    text = re.sub(r"\s*—\s*", ", ", text)
    return text


def parse_skills() -> list[dict]:
    md = (ROOT / "SKILLS.md").read_text(encoding="utf-8")
    rows = []
    for m in re.finditer(r"^\|\s*\[`([^`]+)`\]\(([^)]+)\)\s*\|\s*([^|]+?)\s*\|\s*(.+?)\s*\|\s*$", md, re.M):
        slug, path, licence, desc = m.groups()
        rows.append({
            "slug": slug.strip(),
            "path": path.strip(),
            "licence": deslop(licence.strip()),
            "desc": deslop(desc.strip()),
        })
    return rows


def version() -> str:
    ri = (ROOT / "RELEASE-INFO.txt").read_text(encoding="utf-8")
    m = re.search(r"Version:\s*([0-9]+\.[0-9]+\.[0-9]+)", ri)
    return m.group(1) if m else "0.0.0"


REPO = "https://github.com/jgsystemsconsulting/jgs-se-knowledge-packs"
PAGES = "https://jgsystemsconsulting.github.io/jgs-se-knowledge-packs"


def render(rows: list[dict], ver: str) -> str:
    n_content = len(rows)
    cells = []
    for r in rows:
        slug = html.escape(r["slug"])
        licence = html.escape(r["licence"])
        desc = html.escape(r["desc"])
        href = f"{REPO}/blob/main/{r['path']}"
        # data-text powers the client-side filter (slug + licence + description, lowercased)
        data = html.escape(f"{r['slug']} {r['licence']} {r['desc']}".lower(), quote=True)
        cells.append(
            f'<tr data-text="{data}">'
            f'<td class="slug"><a href="{href}">{slug}</a></td>'
            f'<td class="lic">{licence}</td>'
            f'<td class="desc">{desc}</td></tr>'
        )
    rows_html = "\n".join(cells)

    return f"""<!doctype html>
<!--
  Copyright (c) 2026 JG Systems Consulting Ltd. MIT License (see ../LICENSE).
  SPDX-License-Identifier: MIT
  GENERATED by tooling/gen_packs_page.py from SKILLS.md. Do not hand-edit (RR-B-00).
  RR-B-30 browsable skill reference. Self-contained (inline CSS/JS, no third-party asset).
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pack reference, JGS SE Knowledge Packs ({n_content} skills)</title>
<meta name="description" content="Browse and filter all {n_content} JGS SE Knowledge Pack skills by slug, source licence, and coverage: NASA, NIST, DoD, GAO, FAA, and SEBoK packs for coding agents.">
<link rel="canonical" href="{PAGES}/packs.html">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%230a0a0b'/%3E%3Ctext x='16' y='23' font-family='monospace' font-size='22' font-weight='700' text-anchor='middle' fill='%23f4f2ec'%3E%C2%A7%3C/text%3E%3C/svg%3E">
<meta property="og:type" content="website">
<meta property="og:title" content="Pack reference, JGS SE Knowledge Packs">
<meta property="og:description" content="Browse and filter all {n_content} systems-engineering knowledge-pack skills by slug, source licence, and coverage.">
<meta property="og:url" content="{PAGES}/packs.html">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Pack reference, JGS SE Knowledge Packs">
<meta name="twitter:description" content="Browse and filter all {n_content} systems-engineering knowledge-pack skills.">
<style>
@font-face{{font-family:'JetBrains Mono';src:url('fonts/JetBrainsMono-Regular.woff2') format('woff2');font-weight:400;font-display:swap}}
@font-face{{font-family:'JetBrains Mono';src:url('fonts/JetBrainsMono-Bold.woff2') format('woff2');font-weight:700;font-display:swap}}
@font-face{{font-family:'Inter';src:url('fonts/Inter-Regular.woff2') format('woff2');font-weight:400;font-display:swap}}
@font-face{{font-family:'Inter';src:url('fonts/Inter-SemiBold.woff2') format('woff2');font-weight:600;font-display:swap}}
:root{{
  --ink:#0a0a0b; --ink-2:#111113; --ink-3:#16171a; --ink-4:#1e2024;
  --line:#2a2d33; --line-2:#3a3e46;
  --mute:#6b7078; --mute-2:#8b9099;
  --text:#c7ccd3; --text-hi:#e8ebf0;
  --paper:#f4f2ec; --paper-ink:#0a0a0b;
  --mono:'JetBrains Mono',ui-monospace,'SFMono-Regular',Menlo,Consolas,monospace;
  --sans:'Inter',ui-sans-serif,system-ui,sans-serif;
  --pad-x:clamp(24px,4vw,80px); --pad-section:clamp(48px,6vw,96px);
}}
*{{box-sizing:border-box}}
html{{-webkit-text-size-adjust:100%}}
body{{margin:0;background:var(--ink);color:var(--mute-2);font-family:var(--sans);font-size:16px;line-height:1.6;-webkit-font-smoothing:antialiased}}
.wrap{{max-width:1200px;margin:0 auto;padding-left:var(--pad-x);padding-right:var(--pad-x)}}
a{{color:var(--text-hi);text-decoration:none;border-bottom:1px solid var(--line-2)}}
a:hover{{border-bottom-color:var(--paper)}}
a:focus-visible,input:focus-visible{{outline:2px solid var(--paper);outline-offset:2px}}
h1{{font-family:var(--mono);color:var(--text-hi);letter-spacing:-0.02em;font-weight:700;margin:0;font-size:clamp(1.6rem,4vw,2.4rem)}}
.label{{font-family:var(--mono);text-transform:uppercase;letter-spacing:0.14em;font-size:0.6875rem;font-weight:700;color:var(--mute)}}
.mast{{border-bottom:1px solid var(--line);background:var(--ink-2)}}
.mast .wrap{{display:flex;flex-wrap:wrap;gap:10px 28px;padding-top:12px;padding-bottom:12px}}
.mast .label span{{color:var(--text)}}
header.hd{{border-bottom:1px solid var(--line);padding-top:var(--pad-section);padding-bottom:2rem}}
header.hd p{{margin:1rem 0 0;max-width:64ch;color:var(--text)}}
.tools{{display:flex;flex-wrap:wrap;gap:14px;align-items:center;margin-top:1.6rem}}
input#q{{font-family:var(--mono);font-size:0.9rem;background:var(--ink-2);border:1px solid var(--line);color:var(--text-hi);padding:11px 14px;min-width:min(420px,100%);}}
input#q::placeholder{{color:var(--mute)}}
#count{{font-family:var(--mono);font-size:0.75rem;color:var(--mute-2);text-transform:uppercase;letter-spacing:0.1em}}
.nav{{margin-top:1.4rem;font-family:var(--mono);font-size:0.8rem}}
section{{padding-top:2rem;padding-bottom:var(--pad-section)}}
table{{width:100%;border-collapse:collapse;border:1px solid var(--line)}}
thead th{{font-family:var(--mono);text-transform:uppercase;letter-spacing:0.1em;font-size:0.6875rem;font-weight:700;color:var(--mute);text-align:left;padding:12px 16px;background:var(--ink-2);border-bottom:1px solid var(--line);position:sticky;top:0}}
tbody td{{padding:14px 16px;border-bottom:1px solid var(--line);vertical-align:top;font-size:0.9rem}}
tbody tr:last-child td{{border-bottom:none}}
td.slug a{{font-family:var(--mono);font-weight:700;color:var(--text-hi);font-size:0.85rem;white-space:nowrap}}
td.lic{{font-family:var(--mono);font-size:0.75rem;color:var(--mute-2);white-space:nowrap}}
td.desc{{color:var(--text)}}
tr.hidden{{display:none}}
#empty{{display:none;padding:24px 16px;color:var(--mute-2);font-family:var(--mono);font-size:0.85rem}}
footer{{padding-top:32px;padding-bottom:48px;color:var(--mute);border-top:1px solid var(--line)}}
footer .label{{display:block;margin-bottom:8px}}
@media (max-width:760px){{
  thead{{display:none}}
  table,tbody,tr,td{{display:block;width:100%}}
  table{{border:none}}
  tbody tr{{border:1px solid var(--line);margin-bottom:1px;padding:6px 0;background:var(--ink-2)}}
  tbody td{{border-bottom:none;padding:6px 16px}}
  td.lic{{color:var(--mute);white-space:normal}}
}}
@media (prefers-reduced-motion:reduce){{*{{transition:none!important;animation:none!important}}}}
</style>
</head>
<body>

<div class="mast"><div class="wrap">
  <span class="label">CLASSIFICATION: <span>PUBLIC</span></span>
  <span class="label">LICENCE: <span>MIT (TOOLING)</span></span>
  <span class="label">DOC-ID: <span>JGS-SE-KP/REF</span></span>
  <span class="label">REV: <span>{ver}</span></span>
</div></div>

<header class="hd"><div class="wrap">
  <span class="label">JG Systems Consulting Ltd. · Pack reference</span>
  <h1>The full catalogue, {n_content} skills</h1>
  <p>Every knowledge pack in the release, with its source licence and what it covers. Each pack
  is an Agent Skill you invoke by its slug. Type to filter by name, publisher, licence, or topic.
  Click a slug to open its <code>SKILL.md</code> on GitHub.</p>
  <div class="tools">
    <input id="q" type="search" placeholder="filter, e.g. nasa, risk, public domain, CC BY" aria-label="Filter packs">
    <span id="count"></span>
  </div>
  <div class="nav"><a href="index.html">&larr; Back to the overview</a></div>
</div></header>

<section><div class="wrap">
  <table>
    <thead><tr><th>Pack</th><th>Source licence</th><th>What it covers</th></tr></thead>
    <tbody id="rows">
{rows_html}
    </tbody>
  </table>
  <div id="empty">No packs match that filter.</div>
</div></section>

<footer><div class="wrap">
  <span class="label">JG Systems Consulting Ltd. · 2026</span>
  <p style="margin:0;font-size:0.9rem">
    <a href="index.html">Overview</a> ·
    <a href="{REPO}">Repository</a> ·
    <a href="{REPO}/blob/main/SKILLS.md">SKILLS.md</a> ·
    <a href="{REPO}/blob/main/docs/skill-usage.md">Usage</a>
  </p>
</div></footer>

<script>
(function(){{
  var q=document.getElementById('q'),rows=[].slice.call(document.querySelectorAll('#rows tr')),
      count=document.getElementById('count'),empty=document.getElementById('empty'),total=rows.length;
  function upd(){{
    var t=q.value.trim().toLowerCase(),shown=0;
    rows.forEach(function(r){{
      var hit=!t||r.getAttribute('data-text').indexOf(t)>-1;
      r.classList.toggle('hidden',!hit); if(hit)shown++;
    }});
    count.textContent=shown+' / '+total+' shown';
    empty.style.display=shown?'none':'block';
  }}
  q.addEventListener('input',upd); upd();
}})();
</script>

</body>
</html>
"""


def main() -> int:
    rows = parse_skills()
    if not rows:
        print("ERROR: no pack rows parsed from SKILLS.md", file=sys.stderr)
        return 1
    out = ROOT / "docs" / "packs.html"
    out.write_text(render(rows, version()), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(rows)} packs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
